using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DriverChallenge
{
    public class PaisPiloto
    {
        public List<string> NacionalidadesTop1 { get; } = new List<string>
        {
            "Brasil",
            "Alemanha",
            "Austrália",
            "Bélgica",
            "Canadá",
            "Dinamarca",
            "Espanha",
            "Estados Unidos",
            "França",
            "Inglaterra",
            "Itália",
            "Japão",
            "México",
            "Noruega",
            "Holanda",
            // Adicione outras nacionalidades conforme necessário
        };
        public List<string> NacionalidadesTop2 { get; } = new List<string>
        {
            "Brasil",
            "Alemanha",
            "Austrália",
            "Bélgica",
            "Canadá",
            "Dinamarca",
            "Espanha",
            "Estados Unidos",
            "França",
            "Inglaterra",
            "Itália",
            "Japão",
            "México",
            "Noruega",
            "Holanda",
            "Arábia Saudita",
            "Argentina",
            "Catar",
            "China",
            "Emirados Árabes Unidos",
            "África do Sul",
            "Israel",
            "Mônaco",
            "Nova Zelândia",
            "Polônia",
            "Portugal",
            "Rússia",
            "Suécia",
            "Suíça",
            "Áustria",
            // Adicione outras nacionalidades conforme necessário
        };
        public List<string> NacionalidadesTop3 { get; } = new List<string>
        {
            "Brasil",
            "Alemanha",
            "Austrália",
            "Bélgica",
            "Canadá",
            "Dinamarca",
            "Espanha",
            "Estados Unidos",
            "França",
            "Inglaterra",
            "Itália",
            "Japão",
            "México",
            "Noruega",
            "Holanda",
            "Arábia Saudita",
            "Argentina",
            "Catar",
            "China",
            "Emirados Árabes Unidos",
            "África do Sul",
            "Israel",
            "Mônaco",
            "Nova Zelândia",
            "Polônia",
            "Portugal",
            "Rússia",
            "Suécia",
            "Suíça",
            "Áustria",
            "Albânia",
            "Argélia",
            "Armênia",
            "Bahrein",
            "Chile",
            "Colômbia",
            "Egito",
            "Finlândia",
            "Grécia",
            "Índia",
            "Irlanda",
            "Islândia",
            "Marrocos",
            "Turquia",
            // Adicione outras nacionalidades conforme necessário
        };
        public List<string> NacionalidadesTop4 { get; } = new List<string>
        {
            "Brasil",
            "Alemanha",
            "Austrália",
            "Bélgica",
            "Canadá",
            "Dinamarca",
            "Espanha",
            "Estados Unidos",
            "França",
            "Inglaterra",
            "Itália",
            "Japão",
            "México",
            "Noruega",
            "Holanda",
            "Arábia Saudita",
            "Argentina",
            "Catar",
            "China",
            "Emirados Árabes Unidos",
            "África do Sul",
            "Israel",
            "Mônaco",
            "Nova Zelândia",
            "Polônia",
            "Portugal",
            "Rússia",
            "Suécia",
            "Suíça",
            "Áustria",
            "Albânia",
            "Argélia",
            "Armênia",
            "Bahrein",
            "Chile",
            "Colômbia",
            "Egito",
            "Finlândia",
            "Grécia",
            "Índia",
            "Irlanda",
            "Islândia",
            "Marrocos",
            "Turquia",
            "Afeganistão",
            "Andorra",
            "Angola",
            "Azerbaijão",
            "Bangladesh",
            "Bósnia - Herzegovina",
            "Camarões",
            "Congo",
            "Corei do Sul",
            "Costa do Marfim",
            "Equador",
            "Eslováquia",
            "Eslovênia",
            "Estônia",
            "Hungria",
            "Nigéria",
            "Paraguai",
            "Peru",
            "República Tcheca",
            "Sérvia",
            "Singapura",
            "Tailândia",
            "Tunísia",
            "Ucrânia",
            "Uruguai",
            "Bahamas",
            "Barbados",
            "Bielorrússia",
            "Bulgária",
            "Costa Rica",
            "Cuba",
            // Adicione outras nacionalidades conforme necessário
        };
    }
}
